# Generated by Django 4.0.3 on 2022-05-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteblog', '0004_alter_userprofile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
