# Generated by Django 4.0.3 on 2022-05-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteblog', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lm',
        ),
    ]
