# Generated by Django 4.0.3 on 2022-05-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteblog', '0009_remove_profile_lm'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
