# Generated by Django 4.0.3 on 2022-05-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteblog', '0010_blogmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.ImageField(default='defaultbg.jpg', upload_to='background_pics'),
        ),
    ]
