# Generated by Django 4.0.3 on 2022-05-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteblog', '0011_profile_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='background',
            field=models.ImageField(default='defaultbg.jpg', upload_to='postbg'),
        ),
    ]
