# Generated by Django 4.0.3 on 2022-05-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteblog', '0013_blogmodel_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='likes',
        ),
    ]
