# Generated by Django 4.0.3 on 2022-05-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteblog', '0015_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='likes',
            new_name='blogmodel',
        ),
    ]
